project:
  type: website

website:
  title: "CRT Musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/codyrtuttle
      - icon: twitter
        href: https://twitter.com/codytuttle
format:
  html:
    theme: journal
    css: styles.css

editor: source

